/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from './common';

export declare namespace PikaPerpV2 {
  export type ProductStruct = {
    feed: PromiseOrValue<string>;
    maxLeverage: PromiseOrValue<BigNumberish>;
    fee: PromiseOrValue<BigNumberish>;
    isActive: PromiseOrValue<boolean>;
    openInterestLong: PromiseOrValue<BigNumberish>;
    openInterestShort: PromiseOrValue<BigNumberish>;
    interest: PromiseOrValue<BigNumberish>;
    liquidationThreshold: PromiseOrValue<BigNumberish>;
    liquidationBounty: PromiseOrValue<BigNumberish>;
    minPriceChange: PromiseOrValue<BigNumberish>;
    weight: PromiseOrValue<BigNumberish>;
    reserve: PromiseOrValue<BigNumberish>;
  };

  export type ProductStructOutput = [
    string,
    BigNumber,
    number,
    boolean,
    BigNumber,
    BigNumber,
    number,
    number,
    number,
    number,
    number,
    BigNumber,
  ] & {
    feed: string;
    maxLeverage: BigNumber;
    fee: number;
    isActive: boolean;
    openInterestLong: BigNumber;
    openInterestShort: BigNumber;
    interest: number;
    liquidationThreshold: number;
    liquidationBounty: number;
    minPriceChange: number;
    weight: number;
    reserve: BigNumber;
  };

  export type VaultStruct = {
    cap: PromiseOrValue<BigNumberish>;
    balance: PromiseOrValue<BigNumberish>;
    staked: PromiseOrValue<BigNumberish>;
    shares: PromiseOrValue<BigNumberish>;
    stakingPeriod: PromiseOrValue<BigNumberish>;
  };

  export type VaultStructOutput = [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
    cap: BigNumber;
    balance: BigNumber;
    staked: BigNumber;
    shares: BigNumber;
    stakingPeriod: number;
  };

  export type PositionStruct = {
    productId: PromiseOrValue<BigNumberish>;
    leverage: PromiseOrValue<BigNumberish>;
    price: PromiseOrValue<BigNumberish>;
    oraclePrice: PromiseOrValue<BigNumberish>;
    margin: PromiseOrValue<BigNumberish>;
    owner: PromiseOrValue<string>;
    timestamp: PromiseOrValue<BigNumberish>;
    isLong: PromiseOrValue<boolean>;
  };

  export type PositionStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    boolean,
  ] & {
    productId: BigNumber;
    leverage: BigNumber;
    price: BigNumber;
    oraclePrice: BigNumber;
    margin: BigNumber;
    owner: string;
    timestamp: BigNumber;
    isLong: boolean;
  };

  export type StakeStruct = {
    owner: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
    shares: PromiseOrValue<BigNumberish>;
    timestamp: PromiseOrValue<BigNumberish>;
  };

  export type StakeStructOutput = [string, BigNumber, BigNumber, number] & {
    owner: string;
    amount: BigNumber;
    shares: BigNumber;
    timestamp: number;
  };
}

export interface PikaProtocolVaultInterface extends utils.Interface {
  functions: {
    'BASE()': FunctionFragment;
    'BASE_DECIMALS()': FunctionFragment;
    'addMargin(uint256,uint256)': FunctionFragment;
    'addProduct(uint256,(address,uint72,uint16,bool,uint64,uint64,uint16,uint16,uint16,uint16,uint16,uint64))': FunctionFragment;
    'canLiquidate(uint256)': FunctionFragment;
    'closePosition(uint256,uint256,bool)': FunctionFragment;
    'closePositionWithId(uint256,uint256)': FunctionFragment;
    'distributePikaReward()': FunctionFragment;
    'distributeProtocolReward()': FunctionFragment;
    'distributeVaultReward()': FunctionFragment;
    'exposureMultiplier()': FunctionFragment;
    'getPendingPikaReward()': FunctionFragment;
    'getPendingProtocolReward()': FunctionFragment;
    'getPendingVaultReward()': FunctionFragment;
    'getPosition(address,uint256,bool)': FunctionFragment;
    'getPositionId(address,uint256,bool)': FunctionFragment;
    'getPositions(uint256[])': FunctionFragment;
    'getProduct(uint256)': FunctionFragment;
    'getShare(address)': FunctionFragment;
    'getShareBalance(address)': FunctionFragment;
    'getStake(address)': FunctionFragment;
    'getTotalShare()': FunctionFragment;
    'getVault()': FunctionFragment;
    'liquidatePositions(uint256[])': FunctionFragment;
    'liquidator()': FunctionFragment;
    'maxPositionMargin()': FunctionFragment;
    'maxShift()': FunctionFragment;
    'minMargin()': FunctionFragment;
    'minProfitTime()': FunctionFragment;
    'openPosition(uint256,uint256,bool,uint256)': FunctionFragment;
    'openPositionForUser(address,uint256,uint256,bool,uint256)': FunctionFragment;
    'oracle()': FunctionFragment;
    'owner()': FunctionFragment;
    'pendingPikaReward()': FunctionFragment;
    'pendingProtocolReward()': FunctionFragment;
    'pendingVaultReward()': FunctionFragment;
    'pikaRewardDistributor()': FunctionFragment;
    'pikaRewardRatio()': FunctionFragment;
    'protocolRewardDistributor()': FunctionFragment;
    'protocolRewardRatio()': FunctionFragment;
    'redeem(uint256)': FunctionFragment;
    'releaseMargin(uint256)': FunctionFragment;
    'setCanUserStakeAndAllowPublicLiquidator(bool,bool)': FunctionFragment;
    'setDistributors(address,address,address,address)': FunctionFragment;
    'setExposureMultiplier(uint256)': FunctionFragment;
    'setLiquidator(address)': FunctionFragment;
    'setMargin(uint256,uint256)': FunctionFragment;
    'setMaxShiftAndMinProfitTime(uint256,uint256)': FunctionFragment;
    'setOracle(address)': FunctionFragment;
    'setOwner(address)': FunctionFragment;
    'setRewardRatio(uint256,uint256)': FunctionFragment;
    'stake(uint256)': FunctionFragment;
    'stakeForUser(uint256,address)': FunctionFragment;
    'token()': FunctionFragment;
    'tokenBase()': FunctionFragment;
    'tokenDecimal()': FunctionFragment;
    'totalOpenInterest()': FunctionFragment;
    'totalWeight()': FunctionFragment;
    'updateProduct(uint256,(address,uint72,uint16,bool,uint64,uint64,uint16,uint16,uint16,uint16,uint16,uint64))': FunctionFragment;
    'updateVault((uint96,uint96,uint64,uint64,uint32))': FunctionFragment;
    'utilizationMultiplier()': FunctionFragment;
    'vaultRewardDistributor()': FunctionFragment;
    'vaultTokenReward()': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'BASE'
      | 'BASE_DECIMALS'
      | 'addMargin'
      | 'addProduct'
      | 'canLiquidate'
      | 'closePosition'
      | 'closePositionWithId'
      | 'distributePikaReward'
      | 'distributeProtocolReward'
      | 'distributeVaultReward'
      | 'exposureMultiplier'
      | 'getPendingPikaReward'
      | 'getPendingProtocolReward'
      | 'getPendingVaultReward'
      | 'getPosition'
      | 'getPositionId'
      | 'getPositions'
      | 'getProduct'
      | 'getShare'
      | 'getShareBalance'
      | 'getStake'
      | 'getTotalShare'
      | 'getVault'
      | 'liquidatePositions'
      | 'liquidator'
      | 'maxPositionMargin'
      | 'maxShift'
      | 'minMargin'
      | 'minProfitTime'
      | 'openPosition'
      | 'openPositionForUser'
      | 'oracle'
      | 'owner'
      | 'pendingPikaReward'
      | 'pendingProtocolReward'
      | 'pendingVaultReward'
      | 'pikaRewardDistributor'
      | 'pikaRewardRatio'
      | 'protocolRewardDistributor'
      | 'protocolRewardRatio'
      | 'redeem'
      | 'releaseMargin'
      | 'setCanUserStakeAndAllowPublicLiquidator'
      | 'setDistributors'
      | 'setExposureMultiplier'
      | 'setLiquidator'
      | 'setMargin'
      | 'setMaxShiftAndMinProfitTime'
      | 'setOracle'
      | 'setOwner'
      | 'setRewardRatio'
      | 'stake'
      | 'stakeForUser'
      | 'token'
      | 'tokenBase'
      | 'tokenDecimal'
      | 'totalOpenInterest'
      | 'totalWeight'
      | 'updateProduct'
      | 'updateVault'
      | 'utilizationMultiplier'
      | 'vaultRewardDistributor'
      | 'vaultTokenReward',
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'BASE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'BASE_DECIMALS', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'addMargin',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: 'addProduct',
    values: [PromiseOrValue<BigNumberish>, PikaPerpV2.ProductStruct],
  ): string;
  encodeFunctionData(functionFragment: 'canLiquidate', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: 'closePosition',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>],
  ): string;
  encodeFunctionData(
    functionFragment: 'closePositionWithId',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: 'distributePikaReward', values?: undefined): string;
  encodeFunctionData(functionFragment: 'distributeProtocolReward', values?: undefined): string;
  encodeFunctionData(functionFragment: 'distributeVaultReward', values?: undefined): string;
  encodeFunctionData(functionFragment: 'exposureMultiplier', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getPendingPikaReward', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getPendingProtocolReward', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getPendingVaultReward', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'getPosition',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>],
  ): string;
  encodeFunctionData(
    functionFragment: 'getPositionId',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>],
  ): string;
  encodeFunctionData(functionFragment: 'getPositions', values: [PromiseOrValue<BigNumberish>[]]): string;
  encodeFunctionData(functionFragment: 'getProduct', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'getShare', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'getShareBalance', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'getStake', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'getTotalShare', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getVault', values?: undefined): string;
  encodeFunctionData(functionFragment: 'liquidatePositions', values: [PromiseOrValue<BigNumberish>[]]): string;
  encodeFunctionData(functionFragment: 'liquidator', values?: undefined): string;
  encodeFunctionData(functionFragment: 'maxPositionMargin', values?: undefined): string;
  encodeFunctionData(functionFragment: 'maxShift', values?: undefined): string;
  encodeFunctionData(functionFragment: 'minMargin', values?: undefined): string;
  encodeFunctionData(functionFragment: 'minProfitTime', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'openPosition',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'openPositionForUser',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>,
    ],
  ): string;
  encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'pendingPikaReward', values?: undefined): string;
  encodeFunctionData(functionFragment: 'pendingProtocolReward', values?: undefined): string;
  encodeFunctionData(functionFragment: 'pendingVaultReward', values?: undefined): string;
  encodeFunctionData(functionFragment: 'pikaRewardDistributor', values?: undefined): string;
  encodeFunctionData(functionFragment: 'pikaRewardRatio', values?: undefined): string;
  encodeFunctionData(functionFragment: 'protocolRewardDistributor', values?: undefined): string;
  encodeFunctionData(functionFragment: 'protocolRewardRatio', values?: undefined): string;
  encodeFunctionData(functionFragment: 'redeem', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'releaseMargin', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: 'setCanUserStakeAndAllowPublicLiquidator',
    values: [PromiseOrValue<boolean>, PromiseOrValue<boolean>],
  ): string;
  encodeFunctionData(
    functionFragment: 'setDistributors',
    values: [PromiseOrValue<string>, PromiseOrValue<string>, PromiseOrValue<string>, PromiseOrValue<string>],
  ): string;
  encodeFunctionData(functionFragment: 'setExposureMultiplier', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'setLiquidator', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(
    functionFragment: 'setMargin',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: 'setMaxShiftAndMinProfitTime',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: 'setOracle', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'setOwner', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(
    functionFragment: 'setRewardRatio',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: 'stake', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: 'stakeForUser',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>],
  ): string;
  encodeFunctionData(functionFragment: 'token', values?: undefined): string;
  encodeFunctionData(functionFragment: 'tokenBase', values?: undefined): string;
  encodeFunctionData(functionFragment: 'tokenDecimal', values?: undefined): string;
  encodeFunctionData(functionFragment: 'totalOpenInterest', values?: undefined): string;
  encodeFunctionData(functionFragment: 'totalWeight', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'updateProduct',
    values: [PromiseOrValue<BigNumberish>, PikaPerpV2.ProductStruct],
  ): string;
  encodeFunctionData(functionFragment: 'updateVault', values: [PikaPerpV2.VaultStruct]): string;
  encodeFunctionData(functionFragment: 'utilizationMultiplier', values?: undefined): string;
  encodeFunctionData(functionFragment: 'vaultRewardDistributor', values?: undefined): string;
  encodeFunctionData(functionFragment: 'vaultTokenReward', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'BASE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'BASE_DECIMALS', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'addMargin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'addProduct', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'canLiquidate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'closePosition', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'closePositionWithId', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'distributePikaReward', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'distributeProtocolReward', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'distributeVaultReward', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'exposureMultiplier', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getPendingPikaReward', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getPendingProtocolReward', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getPendingVaultReward', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getPosition', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getPositionId', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getPositions', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getProduct', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getShare', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getShareBalance', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getStake', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getTotalShare', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getVault', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'liquidatePositions', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'liquidator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'maxPositionMargin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'maxShift', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'minMargin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'minProfitTime', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'openPosition', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'openPositionForUser', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'pendingPikaReward', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'pendingProtocolReward', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'pendingVaultReward', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'pikaRewardDistributor', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'pikaRewardRatio', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'protocolRewardDistributor', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'protocolRewardRatio', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'releaseMargin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setCanUserStakeAndAllowPublicLiquidator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setDistributors', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setExposureMultiplier', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setLiquidator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setMargin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setMaxShiftAndMinProfitTime', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setOracle', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setRewardRatio', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'stakeForUser', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'tokenBase', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'tokenDecimal', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'totalOpenInterest', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'totalWeight', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'updateProduct', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'updateVault', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'utilizationMultiplier', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'vaultRewardDistributor', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'vaultTokenReward', data: BytesLike): Result;

  events: {
    'AddMargin(uint256,address,uint256,uint256,uint256)': EventFragment;
    'ClosePosition(uint256,address,uint256,uint256,uint256,uint256,uint256,uint256,int256,bool)': EventFragment;
    'NewPosition(uint256,address,uint256,bool,uint256,uint256,uint256,uint256,uint256)': EventFragment;
    'OracleUpdated(address)': EventFragment;
    'OwnerUpdated(address)': EventFragment;
    'PikaRewardDistributed(address,uint256)': EventFragment;
    'PositionLiquidated(uint256,address,uint256,uint256)': EventFragment;
    'ProductAdded(uint256,tuple)': EventFragment;
    'ProductUpdated(uint256,tuple)': EventFragment;
    'ProtocolRewardDistributed(address,uint256)': EventFragment;
    'Redeemed(address,uint256,uint256,uint256,bool)': EventFragment;
    'RewardRatioUpdated(uint256,uint256)': EventFragment;
    'Staked(address,uint256,uint256)': EventFragment;
    'VaultRewardDistributed(address,uint256)': EventFragment;
    'VaultUpdated(tuple)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'AddMargin'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'ClosePosition'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'NewPosition'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'OracleUpdated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'OwnerUpdated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'PikaRewardDistributed'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'PositionLiquidated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'ProductAdded'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'ProductUpdated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'ProtocolRewardDistributed'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Redeemed'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'RewardRatioUpdated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Staked'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'VaultRewardDistributed'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'VaultUpdated'): EventFragment;
}

export interface AddMarginEventObject {
  positionId: BigNumber;
  user: string;
  margin: BigNumber;
  newMargin: BigNumber;
  newLeverage: BigNumber;
}
export type AddMarginEvent = TypedEvent<[BigNumber, string, BigNumber, BigNumber, BigNumber], AddMarginEventObject>;

export type AddMarginEventFilter = TypedEventFilter<AddMarginEvent>;

export interface ClosePositionEventObject {
  positionId: BigNumber;
  user: string;
  productId: BigNumber;
  price: BigNumber;
  entryPrice: BigNumber;
  margin: BigNumber;
  leverage: BigNumber;
  fee: BigNumber;
  pnl: BigNumber;
  wasLiquidated: boolean;
}
export type ClosePositionEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, boolean],
  ClosePositionEventObject
>;

export type ClosePositionEventFilter = TypedEventFilter<ClosePositionEvent>;

export interface NewPositionEventObject {
  positionId: BigNumber;
  user: string;
  productId: BigNumber;
  isLong: boolean;
  price: BigNumber;
  oraclePrice: BigNumber;
  margin: BigNumber;
  leverage: BigNumber;
  fee: BigNumber;
}
export type NewPositionEvent = TypedEvent<
  [BigNumber, string, BigNumber, boolean, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  NewPositionEventObject
>;

export type NewPositionEventFilter = TypedEventFilter<NewPositionEvent>;

export interface OracleUpdatedEventObject {
  newOracle: string;
}
export type OracleUpdatedEvent = TypedEvent<[string], OracleUpdatedEventObject>;

export type OracleUpdatedEventFilter = TypedEventFilter<OracleUpdatedEvent>;

export interface OwnerUpdatedEventObject {
  newOwner: string;
}
export type OwnerUpdatedEvent = TypedEvent<[string], OwnerUpdatedEventObject>;

export type OwnerUpdatedEventFilter = TypedEventFilter<OwnerUpdatedEvent>;

export interface PikaRewardDistributedEventObject {
  to: string;
  amount: BigNumber;
}
export type PikaRewardDistributedEvent = TypedEvent<[string, BigNumber], PikaRewardDistributedEventObject>;

export type PikaRewardDistributedEventFilter = TypedEventFilter<PikaRewardDistributedEvent>;

export interface PositionLiquidatedEventObject {
  positionId: BigNumber;
  liquidator: string;
  liquidatorReward: BigNumber;
  remainingReward: BigNumber;
}
export type PositionLiquidatedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  PositionLiquidatedEventObject
>;

export type PositionLiquidatedEventFilter = TypedEventFilter<PositionLiquidatedEvent>;

export interface ProductAddedEventObject {
  productId: BigNumber;
  product: PikaPerpV2.ProductStructOutput;
}
export type ProductAddedEvent = TypedEvent<[BigNumber, PikaPerpV2.ProductStructOutput], ProductAddedEventObject>;

export type ProductAddedEventFilter = TypedEventFilter<ProductAddedEvent>;

export interface ProductUpdatedEventObject {
  productId: BigNumber;
  product: PikaPerpV2.ProductStructOutput;
}
export type ProductUpdatedEvent = TypedEvent<[BigNumber, PikaPerpV2.ProductStructOutput], ProductUpdatedEventObject>;

export type ProductUpdatedEventFilter = TypedEventFilter<ProductUpdatedEvent>;

export interface ProtocolRewardDistributedEventObject {
  to: string;
  amount: BigNumber;
}
export type ProtocolRewardDistributedEvent = TypedEvent<[string, BigNumber], ProtocolRewardDistributedEventObject>;

export type ProtocolRewardDistributedEventFilter = TypedEventFilter<ProtocolRewardDistributedEvent>;

export interface RedeemedEventObject {
  user: string;
  amount: BigNumber;
  shares: BigNumber;
  shareBalance: BigNumber;
  isFullRedeem: boolean;
}
export type RedeemedEvent = TypedEvent<[string, BigNumber, BigNumber, BigNumber, boolean], RedeemedEventObject>;

export type RedeemedEventFilter = TypedEventFilter<RedeemedEvent>;

export interface RewardRatioUpdatedEventObject {
  protocolRewardRatio: BigNumber;
  pikaRewardRatio: BigNumber;
}
export type RewardRatioUpdatedEvent = TypedEvent<[BigNumber, BigNumber], RewardRatioUpdatedEventObject>;

export type RewardRatioUpdatedEventFilter = TypedEventFilter<RewardRatioUpdatedEvent>;

export interface StakedEventObject {
  user: string;
  amount: BigNumber;
  shares: BigNumber;
}
export type StakedEvent = TypedEvent<[string, BigNumber, BigNumber], StakedEventObject>;

export type StakedEventFilter = TypedEventFilter<StakedEvent>;

export interface VaultRewardDistributedEventObject {
  to: string;
  amount: BigNumber;
}
export type VaultRewardDistributedEvent = TypedEvent<[string, BigNumber], VaultRewardDistributedEventObject>;

export type VaultRewardDistributedEventFilter = TypedEventFilter<VaultRewardDistributedEvent>;

export interface VaultUpdatedEventObject {
  vault: PikaPerpV2.VaultStructOutput;
}
export type VaultUpdatedEvent = TypedEvent<[PikaPerpV2.VaultStructOutput], VaultUpdatedEventObject>;

export type VaultUpdatedEventFilter = TypedEventFilter<VaultUpdatedEvent>;

export interface PikaProtocolVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PikaProtocolVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BASE(overrides?: CallOverrides): Promise<[BigNumber]>;

    BASE_DECIMALS(overrides?: CallOverrides): Promise<[BigNumber]>;

    addMargin(
      positionId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    addProduct(
      productId: PromiseOrValue<BigNumberish>,
      _product: PikaPerpV2.ProductStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    canLiquidate(positionId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[boolean]>;

    closePosition(
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    closePositionWithId(
      positionId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    distributePikaReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

    distributeProtocolReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

    distributeVaultReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

    exposureMultiplier(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPendingPikaReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPendingProtocolReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPendingVaultReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPosition(
      account: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: CallOverrides,
    ): Promise<
      [PikaPerpV2.PositionStructOutput] & {
        position: PikaPerpV2.PositionStructOutput;
      }
    >;

    getPositionId(
      account: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    getPositions(
      positionIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides,
    ): Promise<
      [PikaPerpV2.PositionStructOutput[]] & {
        _positions: PikaPerpV2.PositionStructOutput[];
      }
    >;

    getProduct(
      productId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[PikaPerpV2.ProductStructOutput]>;

    getShare(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[BigNumber]>;

    getShareBalance(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[BigNumber]>;

    getStake(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[PikaPerpV2.StakeStructOutput]>;

    getTotalShare(overrides?: CallOverrides): Promise<[BigNumber]>;

    getVault(overrides?: CallOverrides): Promise<[PikaPerpV2.VaultStructOutput]>;

    liquidatePositions(
      positionIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    liquidator(overrides?: CallOverrides): Promise<[string]>;

    maxPositionMargin(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxShift(overrides?: CallOverrides): Promise<[BigNumber]>;

    minMargin(overrides?: CallOverrides): Promise<[BigNumber]>;

    minProfitTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    openPosition(
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      leverage: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    openPositionForUser(
      user: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      leverage: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pendingPikaReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    pendingProtocolReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    pendingVaultReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    pikaRewardDistributor(overrides?: CallOverrides): Promise<[string]>;

    pikaRewardRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    protocolRewardDistributor(overrides?: CallOverrides): Promise<[string]>;

    protocolRewardRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    redeem(
      shares: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    releaseMargin(
      positionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setCanUserStakeAndAllowPublicLiquidator(
      _canUserStake: PromiseOrValue<boolean>,
      _allowPublicLiquidator: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setDistributors(
      _protocolRewardDistributor: PromiseOrValue<string>,
      _pikaRewardDistributor: PromiseOrValue<string>,
      _vaultRewardDistributor: PromiseOrValue<string>,
      _vaultTokenReward: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setExposureMultiplier(
      _exposureMultiplier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setLiquidator(
      _liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setMargin(
      _minMargin: PromiseOrValue<BigNumberish>,
      _maxPositionMargin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setMaxShiftAndMinProfitTime(
      _maxShift: PromiseOrValue<BigNumberish>,
      _minProfitTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setOracle(
      _oracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setOwner(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setRewardRatio(
      _protocolRewardRatio: PromiseOrValue<BigNumberish>,
      _pikaRewardRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    stake(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    stakeForUser(
      amount: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    token(overrides?: CallOverrides): Promise<[string]>;

    tokenBase(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokenDecimal(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalOpenInterest(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalWeight(overrides?: CallOverrides): Promise<[BigNumber]>;

    updateProduct(
      productId: PromiseOrValue<BigNumberish>,
      _product: PikaPerpV2.ProductStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    updateVault(
      _vault: PikaPerpV2.VaultStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    utilizationMultiplier(overrides?: CallOverrides): Promise<[BigNumber]>;

    vaultRewardDistributor(overrides?: CallOverrides): Promise<[string]>;

    vaultTokenReward(overrides?: CallOverrides): Promise<[string]>;
  };

  BASE(overrides?: CallOverrides): Promise<BigNumber>;

  BASE_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

  addMargin(
    positionId: PromiseOrValue<BigNumberish>,
    margin: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  addProduct(
    productId: PromiseOrValue<BigNumberish>,
    _product: PikaPerpV2.ProductStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  canLiquidate(positionId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<boolean>;

  closePosition(
    productId: PromiseOrValue<BigNumberish>,
    margin: PromiseOrValue<BigNumberish>,
    isLong: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  closePositionWithId(
    positionId: PromiseOrValue<BigNumberish>,
    margin: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  distributePikaReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

  distributeProtocolReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

  distributeVaultReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

  exposureMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

  getPendingPikaReward(overrides?: CallOverrides): Promise<BigNumber>;

  getPendingProtocolReward(overrides?: CallOverrides): Promise<BigNumber>;

  getPendingVaultReward(overrides?: CallOverrides): Promise<BigNumber>;

  getPosition(
    account: PromiseOrValue<string>,
    productId: PromiseOrValue<BigNumberish>,
    isLong: PromiseOrValue<boolean>,
    overrides?: CallOverrides,
  ): Promise<PikaPerpV2.PositionStructOutput>;

  getPositionId(
    account: PromiseOrValue<string>,
    productId: PromiseOrValue<BigNumberish>,
    isLong: PromiseOrValue<boolean>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  getPositions(
    positionIds: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides,
  ): Promise<PikaPerpV2.PositionStructOutput[]>;

  getProduct(
    productId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<PikaPerpV2.ProductStructOutput>;

  getShare(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

  getShareBalance(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

  getStake(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PikaPerpV2.StakeStructOutput>;

  getTotalShare(overrides?: CallOverrides): Promise<BigNumber>;

  getVault(overrides?: CallOverrides): Promise<PikaPerpV2.VaultStructOutput>;

  liquidatePositions(
    positionIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  liquidator(overrides?: CallOverrides): Promise<string>;

  maxPositionMargin(overrides?: CallOverrides): Promise<BigNumber>;

  maxShift(overrides?: CallOverrides): Promise<BigNumber>;

  minMargin(overrides?: CallOverrides): Promise<BigNumber>;

  minProfitTime(overrides?: CallOverrides): Promise<BigNumber>;

  openPosition(
    productId: PromiseOrValue<BigNumberish>,
    margin: PromiseOrValue<BigNumberish>,
    isLong: PromiseOrValue<boolean>,
    leverage: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  openPositionForUser(
    user: PromiseOrValue<string>,
    productId: PromiseOrValue<BigNumberish>,
    margin: PromiseOrValue<BigNumberish>,
    isLong: PromiseOrValue<boolean>,
    leverage: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  oracle(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  pendingPikaReward(overrides?: CallOverrides): Promise<BigNumber>;

  pendingProtocolReward(overrides?: CallOverrides): Promise<BigNumber>;

  pendingVaultReward(overrides?: CallOverrides): Promise<BigNumber>;

  pikaRewardDistributor(overrides?: CallOverrides): Promise<string>;

  pikaRewardRatio(overrides?: CallOverrides): Promise<BigNumber>;

  protocolRewardDistributor(overrides?: CallOverrides): Promise<string>;

  protocolRewardRatio(overrides?: CallOverrides): Promise<BigNumber>;

  redeem(
    shares: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  releaseMargin(
    positionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setCanUserStakeAndAllowPublicLiquidator(
    _canUserStake: PromiseOrValue<boolean>,
    _allowPublicLiquidator: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setDistributors(
    _protocolRewardDistributor: PromiseOrValue<string>,
    _pikaRewardDistributor: PromiseOrValue<string>,
    _vaultRewardDistributor: PromiseOrValue<string>,
    _vaultTokenReward: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setExposureMultiplier(
    _exposureMultiplier: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setLiquidator(
    _liquidator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setMargin(
    _minMargin: PromiseOrValue<BigNumberish>,
    _maxPositionMargin: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setMaxShiftAndMinProfitTime(
    _maxShift: PromiseOrValue<BigNumberish>,
    _minProfitTime: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setOracle(
    _oracle: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setOwner(
    _owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setRewardRatio(
    _protocolRewardRatio: PromiseOrValue<BigNumberish>,
    _pikaRewardRatio: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  stake(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  stakeForUser(
    amount: PromiseOrValue<BigNumberish>,
    user: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  token(overrides?: CallOverrides): Promise<string>;

  tokenBase(overrides?: CallOverrides): Promise<BigNumber>;

  tokenDecimal(overrides?: CallOverrides): Promise<BigNumber>;

  totalOpenInterest(overrides?: CallOverrides): Promise<BigNumber>;

  totalWeight(overrides?: CallOverrides): Promise<BigNumber>;

  updateProduct(
    productId: PromiseOrValue<BigNumberish>,
    _product: PikaPerpV2.ProductStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  updateVault(
    _vault: PikaPerpV2.VaultStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  utilizationMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

  vaultRewardDistributor(overrides?: CallOverrides): Promise<string>;

  vaultTokenReward(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    BASE(overrides?: CallOverrides): Promise<BigNumber>;

    BASE_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    addMargin(
      positionId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    addProduct(
      productId: PromiseOrValue<BigNumberish>,
      _product: PikaPerpV2.ProductStruct,
      overrides?: CallOverrides,
    ): Promise<void>;

    canLiquidate(positionId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<boolean>;

    closePosition(
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: CallOverrides,
    ): Promise<void>;

    closePositionWithId(
      positionId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    distributePikaReward(overrides?: CallOverrides): Promise<BigNumber>;

    distributeProtocolReward(overrides?: CallOverrides): Promise<BigNumber>;

    distributeVaultReward(overrides?: CallOverrides): Promise<BigNumber>;

    exposureMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingPikaReward(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingProtocolReward(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingVaultReward(overrides?: CallOverrides): Promise<BigNumber>;

    getPosition(
      account: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: CallOverrides,
    ): Promise<PikaPerpV2.PositionStructOutput>;

    getPositionId(
      account: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getPositions(
      positionIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides,
    ): Promise<PikaPerpV2.PositionStructOutput[]>;

    getProduct(
      productId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PikaPerpV2.ProductStructOutput>;

    getShare(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    getShareBalance(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    getStake(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PikaPerpV2.StakeStructOutput>;

    getTotalShare(overrides?: CallOverrides): Promise<BigNumber>;

    getVault(overrides?: CallOverrides): Promise<PikaPerpV2.VaultStructOutput>;

    liquidatePositions(positionIds: PromiseOrValue<BigNumberish>[], overrides?: CallOverrides): Promise<void>;

    liquidator(overrides?: CallOverrides): Promise<string>;

    maxPositionMargin(overrides?: CallOverrides): Promise<BigNumber>;

    maxShift(overrides?: CallOverrides): Promise<BigNumber>;

    minMargin(overrides?: CallOverrides): Promise<BigNumber>;

    minProfitTime(overrides?: CallOverrides): Promise<BigNumber>;

    openPosition(
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      leverage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    openPositionForUser(
      user: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      leverage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    pendingPikaReward(overrides?: CallOverrides): Promise<BigNumber>;

    pendingProtocolReward(overrides?: CallOverrides): Promise<BigNumber>;

    pendingVaultReward(overrides?: CallOverrides): Promise<BigNumber>;

    pikaRewardDistributor(overrides?: CallOverrides): Promise<string>;

    pikaRewardRatio(overrides?: CallOverrides): Promise<BigNumber>;

    protocolRewardDistributor(overrides?: CallOverrides): Promise<string>;

    protocolRewardRatio(overrides?: CallOverrides): Promise<BigNumber>;

    redeem(shares: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    releaseMargin(positionId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    setCanUserStakeAndAllowPublicLiquidator(
      _canUserStake: PromiseOrValue<boolean>,
      _allowPublicLiquidator: PromiseOrValue<boolean>,
      overrides?: CallOverrides,
    ): Promise<void>;

    setDistributors(
      _protocolRewardDistributor: PromiseOrValue<string>,
      _pikaRewardDistributor: PromiseOrValue<string>,
      _vaultRewardDistributor: PromiseOrValue<string>,
      _vaultTokenReward: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    setExposureMultiplier(_exposureMultiplier: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    setLiquidator(_liquidator: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    setMargin(
      _minMargin: PromiseOrValue<BigNumberish>,
      _maxPositionMargin: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    setMaxShiftAndMinProfitTime(
      _maxShift: PromiseOrValue<BigNumberish>,
      _minProfitTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    setOracle(_oracle: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    setOwner(_owner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    setRewardRatio(
      _protocolRewardRatio: PromiseOrValue<BigNumberish>,
      _pikaRewardRatio: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    stake(amount: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    stakeForUser(
      amount: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;

    tokenBase(overrides?: CallOverrides): Promise<BigNumber>;

    tokenDecimal(overrides?: CallOverrides): Promise<BigNumber>;

    totalOpenInterest(overrides?: CallOverrides): Promise<BigNumber>;

    totalWeight(overrides?: CallOverrides): Promise<BigNumber>;

    updateProduct(
      productId: PromiseOrValue<BigNumberish>,
      _product: PikaPerpV2.ProductStruct,
      overrides?: CallOverrides,
    ): Promise<void>;

    updateVault(_vault: PikaPerpV2.VaultStruct, overrides?: CallOverrides): Promise<void>;

    utilizationMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    vaultRewardDistributor(overrides?: CallOverrides): Promise<string>;

    vaultTokenReward(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    'AddMargin(uint256,address,uint256,uint256,uint256)'(
      positionId?: PromiseOrValue<BigNumberish> | null,
      user?: PromiseOrValue<string> | null,
      margin?: null,
      newMargin?: null,
      newLeverage?: null,
    ): AddMarginEventFilter;
    AddMargin(
      positionId?: PromiseOrValue<BigNumberish> | null,
      user?: PromiseOrValue<string> | null,
      margin?: null,
      newMargin?: null,
      newLeverage?: null,
    ): AddMarginEventFilter;

    'ClosePosition(uint256,address,uint256,uint256,uint256,uint256,uint256,uint256,int256,bool)'(
      positionId?: PromiseOrValue<BigNumberish> | null,
      user?: PromiseOrValue<string> | null,
      productId?: PromiseOrValue<BigNumberish> | null,
      price?: null,
      entryPrice?: null,
      margin?: null,
      leverage?: null,
      fee?: null,
      pnl?: null,
      wasLiquidated?: null,
    ): ClosePositionEventFilter;
    ClosePosition(
      positionId?: PromiseOrValue<BigNumberish> | null,
      user?: PromiseOrValue<string> | null,
      productId?: PromiseOrValue<BigNumberish> | null,
      price?: null,
      entryPrice?: null,
      margin?: null,
      leverage?: null,
      fee?: null,
      pnl?: null,
      wasLiquidated?: null,
    ): ClosePositionEventFilter;

    'NewPosition(uint256,address,uint256,bool,uint256,uint256,uint256,uint256,uint256)'(
      positionId?: PromiseOrValue<BigNumberish> | null,
      user?: PromiseOrValue<string> | null,
      productId?: PromiseOrValue<BigNumberish> | null,
      isLong?: null,
      price?: null,
      oraclePrice?: null,
      margin?: null,
      leverage?: null,
      fee?: null,
    ): NewPositionEventFilter;
    NewPosition(
      positionId?: PromiseOrValue<BigNumberish> | null,
      user?: PromiseOrValue<string> | null,
      productId?: PromiseOrValue<BigNumberish> | null,
      isLong?: null,
      price?: null,
      oraclePrice?: null,
      margin?: null,
      leverage?: null,
      fee?: null,
    ): NewPositionEventFilter;

    'OracleUpdated(address)'(newOracle?: null): OracleUpdatedEventFilter;
    OracleUpdated(newOracle?: null): OracleUpdatedEventFilter;

    'OwnerUpdated(address)'(newOwner?: null): OwnerUpdatedEventFilter;
    OwnerUpdated(newOwner?: null): OwnerUpdatedEventFilter;

    'PikaRewardDistributed(address,uint256)'(to?: null, amount?: null): PikaRewardDistributedEventFilter;
    PikaRewardDistributed(to?: null, amount?: null): PikaRewardDistributedEventFilter;

    'PositionLiquidated(uint256,address,uint256,uint256)'(
      positionId?: PromiseOrValue<BigNumberish> | null,
      liquidator?: PromiseOrValue<string> | null,
      liquidatorReward?: null,
      remainingReward?: null,
    ): PositionLiquidatedEventFilter;
    PositionLiquidated(
      positionId?: PromiseOrValue<BigNumberish> | null,
      liquidator?: PromiseOrValue<string> | null,
      liquidatorReward?: null,
      remainingReward?: null,
    ): PositionLiquidatedEventFilter;

    'ProductAdded(uint256,tuple)'(productId?: null, product?: null): ProductAddedEventFilter;
    ProductAdded(productId?: null, product?: null): ProductAddedEventFilter;

    'ProductUpdated(uint256,tuple)'(productId?: null, product?: null): ProductUpdatedEventFilter;
    ProductUpdated(productId?: null, product?: null): ProductUpdatedEventFilter;

    'ProtocolRewardDistributed(address,uint256)'(to?: null, amount?: null): ProtocolRewardDistributedEventFilter;
    ProtocolRewardDistributed(to?: null, amount?: null): ProtocolRewardDistributedEventFilter;

    'Redeemed(address,uint256,uint256,uint256,bool)'(
      user?: PromiseOrValue<string> | null,
      amount?: null,
      shares?: null,
      shareBalance?: null,
      isFullRedeem?: null,
    ): RedeemedEventFilter;
    Redeemed(
      user?: PromiseOrValue<string> | null,
      amount?: null,
      shares?: null,
      shareBalance?: null,
      isFullRedeem?: null,
    ): RedeemedEventFilter;

    'RewardRatioUpdated(uint256,uint256)'(
      protocolRewardRatio?: null,
      pikaRewardRatio?: null,
    ): RewardRatioUpdatedEventFilter;
    RewardRatioUpdated(protocolRewardRatio?: null, pikaRewardRatio?: null): RewardRatioUpdatedEventFilter;

    'Staked(address,uint256,uint256)'(
      user?: PromiseOrValue<string> | null,
      amount?: null,
      shares?: null,
    ): StakedEventFilter;
    Staked(user?: PromiseOrValue<string> | null, amount?: null, shares?: null): StakedEventFilter;

    'VaultRewardDistributed(address,uint256)'(to?: null, amount?: null): VaultRewardDistributedEventFilter;
    VaultRewardDistributed(to?: null, amount?: null): VaultRewardDistributedEventFilter;

    'VaultUpdated(tuple)'(vault?: null): VaultUpdatedEventFilter;
    VaultUpdated(vault?: null): VaultUpdatedEventFilter;
  };

  estimateGas: {
    BASE(overrides?: CallOverrides): Promise<BigNumber>;

    BASE_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    addMargin(
      positionId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    addProduct(
      productId: PromiseOrValue<BigNumberish>,
      _product: PikaPerpV2.ProductStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    canLiquidate(positionId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    closePosition(
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    closePositionWithId(
      positionId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    distributePikaReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;

    distributeProtocolReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;

    distributeVaultReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;

    exposureMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingPikaReward(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingProtocolReward(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingVaultReward(overrides?: CallOverrides): Promise<BigNumber>;

    getPosition(
      account: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getPositionId(
      account: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getPositions(positionIds: PromiseOrValue<BigNumberish>[], overrides?: CallOverrides): Promise<BigNumber>;

    getProduct(productId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    getShare(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    getShareBalance(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    getStake(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    getTotalShare(overrides?: CallOverrides): Promise<BigNumber>;

    getVault(overrides?: CallOverrides): Promise<BigNumber>;

    liquidatePositions(
      positionIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    liquidator(overrides?: CallOverrides): Promise<BigNumber>;

    maxPositionMargin(overrides?: CallOverrides): Promise<BigNumber>;

    maxShift(overrides?: CallOverrides): Promise<BigNumber>;

    minMargin(overrides?: CallOverrides): Promise<BigNumber>;

    minProfitTime(overrides?: CallOverrides): Promise<BigNumber>;

    openPosition(
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      leverage: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    openPositionForUser(
      user: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      leverage: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pendingPikaReward(overrides?: CallOverrides): Promise<BigNumber>;

    pendingProtocolReward(overrides?: CallOverrides): Promise<BigNumber>;

    pendingVaultReward(overrides?: CallOverrides): Promise<BigNumber>;

    pikaRewardDistributor(overrides?: CallOverrides): Promise<BigNumber>;

    pikaRewardRatio(overrides?: CallOverrides): Promise<BigNumber>;

    protocolRewardDistributor(overrides?: CallOverrides): Promise<BigNumber>;

    protocolRewardRatio(overrides?: CallOverrides): Promise<BigNumber>;

    redeem(
      shares: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    releaseMargin(
      positionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setCanUserStakeAndAllowPublicLiquidator(
      _canUserStake: PromiseOrValue<boolean>,
      _allowPublicLiquidator: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setDistributors(
      _protocolRewardDistributor: PromiseOrValue<string>,
      _pikaRewardDistributor: PromiseOrValue<string>,
      _vaultRewardDistributor: PromiseOrValue<string>,
      _vaultTokenReward: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setExposureMultiplier(
      _exposureMultiplier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setLiquidator(
      _liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setMargin(
      _minMargin: PromiseOrValue<BigNumberish>,
      _maxPositionMargin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setMaxShiftAndMinProfitTime(
      _maxShift: PromiseOrValue<BigNumberish>,
      _minProfitTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setOracle(
      _oracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setOwner(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setRewardRatio(
      _protocolRewardRatio: PromiseOrValue<BigNumberish>,
      _pikaRewardRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    stake(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    stakeForUser(
      amount: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    tokenBase(overrides?: CallOverrides): Promise<BigNumber>;

    tokenDecimal(overrides?: CallOverrides): Promise<BigNumber>;

    totalOpenInterest(overrides?: CallOverrides): Promise<BigNumber>;

    totalWeight(overrides?: CallOverrides): Promise<BigNumber>;

    updateProduct(
      productId: PromiseOrValue<BigNumberish>,
      _product: PikaPerpV2.ProductStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    updateVault(
      _vault: PikaPerpV2.VaultStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    utilizationMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    vaultRewardDistributor(overrides?: CallOverrides): Promise<BigNumber>;

    vaultTokenReward(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BASE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BASE_DECIMALS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addMargin(
      positionId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    addProduct(
      productId: PromiseOrValue<BigNumberish>,
      _product: PikaPerpV2.ProductStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    canLiquidate(positionId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    closePosition(
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    closePositionWithId(
      positionId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    distributePikaReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>;

    distributeProtocolReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>;

    distributeVaultReward(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>;

    exposureMultiplier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPendingPikaReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPendingProtocolReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPendingVaultReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPosition(
      account: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getPositionId(
      account: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getPositions(positionIds: PromiseOrValue<BigNumberish>[], overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getProduct(productId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getShare(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getShareBalance(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStake(stakeOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalShare(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    liquidatePositions(
      positionIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    liquidator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxPositionMargin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxShift(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minMargin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minProfitTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    openPosition(
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      leverage: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    openPositionForUser(
      user: PromiseOrValue<string>,
      productId: PromiseOrValue<BigNumberish>,
      margin: PromiseOrValue<BigNumberish>,
      isLong: PromiseOrValue<boolean>,
      leverage: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingPikaReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingProtocolReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingVaultReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pikaRewardDistributor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pikaRewardRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolRewardDistributor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolRewardRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    redeem(
      shares: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    releaseMargin(
      positionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setCanUserStakeAndAllowPublicLiquidator(
      _canUserStake: PromiseOrValue<boolean>,
      _allowPublicLiquidator: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setDistributors(
      _protocolRewardDistributor: PromiseOrValue<string>,
      _pikaRewardDistributor: PromiseOrValue<string>,
      _vaultRewardDistributor: PromiseOrValue<string>,
      _vaultTokenReward: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setExposureMultiplier(
      _exposureMultiplier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setLiquidator(
      _liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setMargin(
      _minMargin: PromiseOrValue<BigNumberish>,
      _maxPositionMargin: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setMaxShiftAndMinProfitTime(
      _maxShift: PromiseOrValue<BigNumberish>,
      _minProfitTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setOracle(
      _oracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setOwner(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setRewardRatio(
      _protocolRewardRatio: PromiseOrValue<BigNumberish>,
      _pikaRewardRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    stake(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    stakeForUser(
      amount: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenBase(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenDecimal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalOpenInterest(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalWeight(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateProduct(
      productId: PromiseOrValue<BigNumberish>,
      _product: PikaPerpV2.ProductStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    updateVault(
      _vault: PikaPerpV2.VaultStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    utilizationMultiplier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vaultRewardDistributor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vaultTokenReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
