name: Release
on:
  push:
    - package.json
  branches: ['main']

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.2
          run_install: true

      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.1
        id: release

      - uses: actions/setup-node@v1
        if: steps.release.outputs.released == 'true'
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish
        if: steps.release.outputs.released == 'true'
        run: pnpm publish:npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
