name: Release Studio

on:
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.2
          run_install: true

      - name: Prepare Build
        run: pnpm build

      - name: Prepare Release
        run: pnpm release

      - name: Delete Automatic Tag
        run: 'git push --delete origin $(git describe --tags $(git rev-list --tags --max-count=1))'

      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_ZAPPER_BOT }}
          branch: release
          title: 'chore(release): Release ${{ steps.package-version.outputs.current-version }}'
          commit-message: 'chore(release): Release ${{ steps.package-version.outputs.current-version }}'
          body: |
            ⚙️ _This pull request was opened automatically from Zapper-fi/studio._
          base: main
          delete-branch: true
