name: "Validate Semantic PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          wip: true
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
          types: |
            breaking
            revert
            feat
            feature
            fix
            refactor
            docs
            build
            test
            ci
            chore
          
